- name: install package systemd-swap
  package:
    name: systemd-swap
    state: present

- name: create directory /etc/systemd/swap.conf.d
  file:
    path: /etc/systemd/swap.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure systemd-swap - disable zswap
  lineinfile:
    path: /etc/systemd/swap.conf.d/ansible-zramswap.conf
    create: yes
    line: zswap_enabled=0
    mode: 0644

- name: configure systemd-swap - enable zram
  lineinfile:
    path: /etc/systemd/swap.conf.d/ansible-zramswap.conf
    create: yes
    line: zram_enabled=1
    mode: 0644

- name: enable service for systemd-swap
  service:
    name: systemd-swap
    enabled: yes
    state: started
