---
# Debian tasks file for sgaduuw.zramswap
- name: install package zram-tools
  apt:
    name: zram-tools
    state: present
    update_cache: yes
    install_recommends: no

- name: enable service for zram-tools
  service:
    name: zramswap
    enabled: yes
    state: started
