---
# Ubuntu tasks file for sgaduuw.zramswap
- name: install package zram-config
  apt:
    name: zram-config
    state: present
    update_cache: yes
    install_recommends: no

- name: enable service for zram-config
  service:
    name: zram-config
    enabled: yes
    state: started
  tags:
    - molecule-idempotence-notest
